services:
  react-router-rick-morty:
    image: postgres:15
    container_name: react-router-rick-morty
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin12345
      POSTGRES_DB: rickmorty-favorites
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/