name: Release Tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
      
      - name: Get Version from tag
        id: check
        run: |
          VERSION=$GITHUB_REF_NAME
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"
          echo "BUILD_FILENAME=build-$VERSION.tar.gz" >> $GITHUB_OUTPUT
      
      - name: Compress build
        run:  tar -czf ${{ steps.check.outputs.VERSION }} build/ --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rick & Morty - ${{ steps.check.outputs.VERSION }}
          path: ${{ steps.check.outputs.BUILD_FILENAME }}
          if-no-files-found: ignore

      - name: Create release
        id: create_release
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{
            "tag_name":"${{ steps.check.outputs.VERSION }}",
            "name":"Rick & Morty - ${{ steps.check.outputs.VERSION }}",
            "body":"A new version was created"
          }'