name: Release Tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
      
      - name: Get Version from package.json
        id: check
        run: |
          VERSION=$GITHUB_BASE_REF
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"
          BUILD_FILENAME="build-$VERSION.zip"
      
      - name: Compress build
        run: zip -r $BUILD_FILENAME build/

      - name: Create release
        id: create_release
        if: steps.check.outputs.VERSION != ''
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/releases \
          -d '{"tag_name":"$VERSION","target_commitish":"master","name":"$VERSION","body":"A new version was created","draft":false,"prerelease":false,"generate_release_notes":false}'