name: Release Tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
      
      - name: Get Version from package.json
        id: check
        run: |
          VERSION=$GITHUB_REF_NAME
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"
          echo "BUILD_FILENAME=build-$VERSION.tar.gz" >> $GITHUB_ENV
      
      - name: Compress build
        run:  tar -czf $BUILD_FILENAME build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rick & Morty - $VERSION
          path: $BUILD_FILENAME

      - name: Create release
        id: create_release
        if: steps.check.outputs.VERSION != ''
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/releases \
          -d '{"tag_name":"$VERSION","name":"$VERSION","body":"A new version was created"}'